### ISSUE TITLE
Do not override labels of entities

### ISSUE THREAD

**Issue by D063520** [the-qa-company/WikibaseSync#8]
https://github.com/ec-doris/kohesio-backend/issues/63

**Comment by madewild** [comment]
this issue is becoming more presssing... some changes have been made in Wikidata and are affecting us:
Ireland has been renamed "Republic of Ireland": https://www.wikidata.org/wiki/Q27
Austria has been renamed "Republic of Austria" then again reverted to Austria today: https://www.wikidata.org/w/index.php?title=Q40&diff=1567406595&oldid=1567406445

We need to be unaffected by these changes and keep stable country names.

**Comment by D063520** [comment]
https://linkedopendata.eu/wiki/Item:Q25 is now Czechia

**Comment by madewild** [comment]
and https://linkedopendata.eu/wiki/Item:Q2 is Ireland (contrary to https://www.wikidata.org/wiki/Q27 which is "Republic of Ireland")
